id: P004157
initial_creation_type: ocr
source_metadata:
  id: bdr:W30516
  title: བསེ་ཟིན་བྲིས་བཅུ་གསུམ་དུ་གྲགས་པ།
  author: ''
  volumes:
    8b0af8d9f99347f2a1ac1ffce80e70af:
      image_group_id: I1KG6012
      title: ''
      volume_number: 1
      total_pages: 782
