id: P004157
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W30516
  title: བསེ་ཟིན་བྲིས་བཅུ་གསུམ་དུ་གྲགས་པ།
  author: ''
  volumes:
    8b0af8d9f99347f2a1ac1ffce80e70af:
      image_group_id: I1KG6012
      title: ''
      volume_number: 1
      total_pages: 782
      base_file: v001.txt
