id: IC4FAEF94
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T07:43:01+00:00'
last_modified: '2022-06-07T20:40:32.184635+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30516
  title: བསེ་ཟིན་བྲིས་བཅུ་གསུམ་དུ་གྲགས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1A38:
      image_group_id: I1KG6012
      title: ''
      total_pages: 782
      order: 1
      base_file: 1A38.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
